### ISSUE TITLE
Bundle Fails to Start in AEM 6.3

### ISSUE THREAD

**Issue by klcodanr** [axamit/gathercontent-aem-integration#2]
The bundle GatherContent - Corecom.axamit.gc.gathercontent.core failes to start in AEM 6.3. It appears to be an issue with the package definition / versioning of Sling Events between AEM 6.2 and 6.3:

![image](https://user-images.githubusercontent.com/2946250/27204146-39e1cb00-51de-11e7-9184-5419358ac185.png)

**Comment by AntoniBertel** [comment]
Hi @klcodanr,

Thanks for the screenshot. We'll fix it soon.

**Comment by klcodanr** [comment]
Cool @AntoniBertel I did also open a pull request with a fix which works with 6.3.

**Comment by AntoniBertel** [comment]
Yeah, I saw it. Many thanks.
We were thinking of testing all functionality on AEM 6.3
UberJar means that we have to switch to multiple branch to support different AEM versions.
(Release 2 is coming up with new powerful features)

**Comment by sergeymoroz** [comment]
The issue has been fixed. AEM 6.3 is now supported by GC-AEM integration v2.0.
